### ISSUE TITLE
Fails in configure phase

### ISSUE THREAD

**Issue by m0rsch1** [rock-core/drivers-orogen-iodrivers_base#18]
Hi there, on my Ubuntu 16.04 machine I cannot compile this orogen component anymore
because of #17. When I revert that merge I can compile it again.

In the configure log is stated, that Proxy.cpp is not found although it is in the tasks folder:
```
CMake Error at .orogen/iodrivers_base/proxies/CMakeLists.txt:48 (ADD_LIBRARY):
  Cannot find source file:

    Proxy.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Warning (dev) at tasks/CMakeLists.txt:7 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "regen-typekit" of target
  "iodrivers_base-tasks-gnulinux" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error: CMake can not determine linker language for target: iodrivers_base-proxies
CMake Error: Cannot determine link language for target "iodrivers_base-proxies"
```

**Comment by saarnold** [comment]
This is related to the orocos cpp proxy generation.
Did something in the generation of tasks change in case the new subclasses syntax is used?
It appears the `post_generation_hook` callback isn't called anymore.

**Comment by 2maz** [comment]
@doudou: could you pls check the correct behaviour/fix
The iteration behaviour over extension seems to have changed for subclasses, i.e.
Orogen::Gen::RTT_CPP::TaskContextGeneration::generate uses:
```
   extensions.each do ...
```
with extension currently being an empty array for the subclass, so that the post_generation_hook will not be called anymore for a subclass task.
Adapting to the following fixes the behaviour:
```
   each_extension(true) do
```

**Comment by doudou** [comment]
Very possible.

> Adapting to the following fixes the behaviour:

It fixes the behavior for your extension, but breaks the intended behavior.

The code generation only iterates over the extensions at the current level, because it should not generate for another level of the hierarchy - the generation at the other level(s) has already been done.

The problem you probably have is that your extension registers itself only if it is not already present. orogen would have a bug there, where this would always register the extension, which for instance caused the metadata extension to register itself multiple times.

In your case, you *should* always register.

**Comment by 2maz** [comment]
> In your case, you should always register.

K, thx for checking. I let you know whether that fixes the problem.

**Comment by 2maz** [comment]
Indeed registration was guarded. Removal fixed the issue.

@m0rsch1 @chhtz: rock-cpp/orogen_cpp_proxies#2 and rock-cpp/orogen_model_exporter#7

**Comment by chhtz** [comment]
After some internal discussion: 

Applying these patches lets some other orogen tasks fail to configure, e.g., 
https://github.com/rock-drivers/drivers-orogen-camera_usb.git
Fails in:
https://github.com/rock-drivers/drivers-orogen-camera_usb/blob/master/camera_usb.orogen#L4
with error:
```
there is already an extension called CPPProxyPlugin:
#<CPPProxyPlugin:0x00000001c5bb50> (OroGen::ConfigError)
```

I don't have rights to re-open this issue (or should I open a new issue for that?)

**Comment by 2maz** [comment]
@doudou: your prefer to move this issue orogen?

**Comment by jmachowinski** [comment]
Damn, I just merged the patches...

**Comment by 2maz** [comment]
@chhtz updating to new syntax fixes the issue apparently: drivers-orogen-camera_usb/pull/4

**Comment by chhtz** [comment]
It still fails for me, unless I comment out this line in https://github.com/rock-cpp/package_set/blob/master/overrides.rb#L6

    pkg.orogen_options << '--extensions=cpp_proxies,modelExport'

**Comment by 2maz** [comment]
Well, that disables these two orogen extensions globally, i.e. they will not be loaded at all.
Have you tested with a fresh and original rock-core/rock/rock-cpp installation, so no project specific overrides etc.?

**Comment by chhtz** [comment]
I actually just finished doing that:

1. bootstrap fresh rock installation (flavor = master)
2. Add `- github: rock-cpp/package_set` to the `package_sets`
3. Add `- drivers/orogen/camera_usb` to the packages

Build still fails with the following (independent of using https://github.com/rock-drivers/drivers-orogen-camera_usb/pull/4 or not):

    there is already an extension called CPPProxyPlugin: #<CPPProxyPlugin:0x0000000374a4c0> (OroGen::ConfigError)

And it still fails at `using_task_library "camera_base"` in https://github.com/rock-drivers/drivers-orogen-camera_usb/blob/master/camera_usb.orogen#L4

**Comment by chhtz** [comment]
This workaround fixes the issue for me:
https://github.com/entern2017/orogen/commit/c6ac3cd3a43fadfa0f7a97ee258014fef5429422

**Comment by 2maz** [comment]
@chhtz apparently I broke my test setup, so I had a false positive
@doudou the current registration behaviour looks erratic to me, so still a bug in orogen?!

**Comment by doudou** [comment]
> find_extension(obj.name, false)

This should return the extension only if it has been registered on this level of the hierarchy. So, it still looks like you're registering it multiple times. maybe a bug on your side, still ?

**Comment by doudou** [comment]
> and the enabling of the default extension will lead to a call of apply_default_extensions which again calls the method (since all these extensions are default extensions).

Where ? https://github.com/orocos-toolchain/orogen/blob/master/lib/orogen/spec/task_context.rb#L74

**Comment by 2maz** [comment]
TaskContext::apply_default_extensions is only used at: https://github.com/orocos-toolchain/orogen/blob/master/lib/orogen/gen/project.rb#L1024

**Comment by doudou** [comment]
Yes, so I don't understand how the `enable_default_extensions` call at the end of the generated orogen file would cause the extensions to be called another time for the same task context model.

**Comment by 2maz** [comment]
It is not the one of this orogen file, but a dependant one, i.e. this project depends upon the logger: so upon loading of logger.orogen all default extensions are enabled.
Subsequently, camera_base.orogen will be loaded and TaskContext::apply_default_extensions is called for the task_context camera_base::Preprocess. 
This loads the extension for the first time for this task, but the orogen plugins will be registered a second time via find_task_context("camera_base::Preprocess").cpp_proxies

**Comment by doudou** [comment]
Should be fixed by https://github.com/orocos-toolchain/orogen/pull/115
